In [1220]:
import random 
import torch 
import torch.optim as optim
from torch_geometric.nn.models import LightGCN 
from sqlalchemy import create_engine
import pandas as pd
import joblib

## For quick training and testing, we fetch data from Vu's DB directly, instead export and import.

In [ ]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

## You might need adjust the statement below to get data for df depend on where you get data from

In [ ]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, interaction_type
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)

In [ ]:
df.tail()

       user_id  product_id interaction_type
10014      984         168         cart_add
10015      984         157               R5
10016      984         175         cart_add
10017      984         172     wishlist_add
10018      984         159               R5

In [ ]:
user_product_interactions = df[['user_id', 'product_id']].drop_duplicates()
user_product_interactions["user_idx"] = user_product_interactions["user_id"].astype("category").cat.codes
user_product_interactions["product_idx"] = user_product_interactions["product_id"].astype("category").cat.codes

In [ ]:
user_product_interactions.head()

   user_id  product_id  user_idx  product_idx
0      485         258         0          220
1      485         191         0          175
2      485         192         0          176
3      485         201         0          184
4      485         187         0          171

In [ ]:
interactions = user_product_interactions[["user_idx", "product_idx"]].to_numpy()

In [ ]:
num_users = user_product_interactions["user_idx"].nunique()
num_items = user_product_interactions["product_idx"].nunique()
num_nodes = num_users + num_items

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
edge_list = []
for user_idx,item_idx in interactions: 
    edge_list.append((user_idx, num_users + item_idx))
    edge_list.append((num_users + item_idx, user_idx))

In [ ]:
edge_list

[(np.int16(0), np.int16(720)),
 (np.int16(720), np.int16(0)),
 (np.int16(0), np.int16(675)),
 (np.int16(675), np.int16(0)),
 (np.int16(0), np.int16(676)),
 (np.int16(676), np.int16(0)),
 (np.int16(0), np.int16(684)),
 (np.int16(684), np.int16(0)),
 (np.int16(0), np.int16(671)),
 (np.int16(671), np.int16(0)),
 (np.int16(0), np.int16(693)),
 (np.int16(693), np.int16(0)),
 (np.int16(0), np.int16(725)),
 (np.int16(725), np.int16(0)),
 (np.int16(0), np.int16(686)),
 (np.int16(686), np.int16(0)),
 (np.int16(0), np.int16(551)),
 (np.int16(551), np.int16(0)),
 (np.int16(0), np.int16(719)),
 (np.int16(719), np.int16(0)),
 (np.int16(0), np.int16(685)),
 (np.int16(685), np.int16(0)),
 (np.int16(0), np.int16(718)),
 (np.int16(718), np.int16(0)),
 (np.int16(0), np.int16(575)),
 (np.int16(575), np.int16(0)),
 (np.int16(0), np.int16(715)),
 (np.int16(715), np.int16(0)),
 (np.int16(0), np.int16(670)),
 (np.int16(670), np.int16(0)),
 (np.int16(0), np.int16(721)),
 (np.int16(721), np.int16(0)),
 (np.int16(1), np.int16(559)),
 (np.int16(559), np.int16(1)),
 (np.int16(1), np.int16(721)),
 (np.int16(721), np.int16(1)),
 (np.int16(1), np.int16(674)),
 (np.int16(674), np.int16(1)),
 (np.int16(1), np.int16(694)),
 (np.int16(694), np.int16(1)),
 (np.int16(1), np.int16(534)),
 (np.int16(534), np.int16(1)),
 (np.int16(1), np.int16(671)),
 (np.int16(671), np.int16(1)),
 (np.int16(1), np.int16(697)),
 (np.int16(697), np.int16(1)),
 (np.int16(1), np.int16(676)),
 (np.int16(676), np.int16(1)),
 (np.int16(1), np.int16(543)),
 (np.int16(543), np.int16(1)),
 (np.int16(1), np.int16(673)),
 (np.int16(673), np.int16(1)),
 (np.int16(1), np.int16(719)),
 (np.int16(719), np.int16(1)),
 (np.int16(1), np.int16(604)),
 (np.int16(604), np.int16(1)),
 (np.int16(1), np.int16(693)),
 (np.int16(693), np.int16(1)),
 (np.int16(1), np.int16(539)),
 (np.int16(539), np.int16(1)),
 (np.int16(1), np.int16(696)),
 (np.int16(696), np.int16(1)),
 (np.int16(1), np.int16(695)),
 (np.int16(695), np.int16(1)),
 (np.int16(1), np.int16(675)),
 (np.int16(675), np.int16(1)),
 (np.int16(1), np.int16(567)),
 (np.int16(567), np.int16(1)),
 (np.int16(2), np.int16(671)),
 (np.int16(671), np.int16(2)),
 (np.int16(2), np.int16(534)),
 (np.int16(534), np.int16(2)),
 (np.int16(2), np.int16(686)),
 (np.int16(686), np.int16(2)),
 (np.int16(2), np.int16(718)),
 (np.int16(718), np.int16(2)),
 (np.int16(2), np.int16(693)),
 (np.int16(693), np.int16(2)),
 (np.int16(2), np.int16(699)),
 (np.int16(699), np.int16(2)),
 (np.int16(2), np.int16(685)),
 (np.int16(685), np.int16(2)),
 (np.int16(2), np.int16(695)),
 (np.int16(695), np.int16(2)),
 (np.int16(2), np.int16(698)),
 (np.int16(698), np.int16(2)),
 (np.int16(2), np.int16(676)),
 (np.int16(676), np.int16(2)),
 (np.int16(2), np.int16(539)),
 (np.int16(539), np.int16(2)),
 (np.int16(2), np.int16(697)),
 (np.int16(697), np.int16(2)),
 (np.int16(2), np.int16(696)),
 (np.int16(696), np.int16(2)),
 (np.int16(2), np.int16(677)),
 (np.int16(677), np.int16(2)),
 (np.int16(2), np.int16(674)),
 (np.int16(674), np.int16(2)),
 (np.int16(2), np.int16(675)),
 (np.int16(675), np.int16(2)),
 (np.int16(2), np.int16(537)),
 (np.int16(537), np.int16(2)),
 (np.int16(2), np.int16(738)),
 (np.int16(738), np.int16(2)),
 (np.int16(3), np.int16(673)),
 (np.int16(673), np.int16(3)),
 (np.int16(3), np.int16(507)),
 (np.int16(507), np.int16(3)),
 (np.int16(3), np.int16(719)),
 (np.int16(719), np.int16(3)),
 (np.int16(3), np.int16(675)),
 (np.int16(675), np.int16(3)),
 (np.int16(3), np.int16(543)),
 (np.int16(543), np.int16(3)),
 (np.int16(3), np.int16(677)),
 (np.int16(677), np.int16(3)),
 (np.int16(3), np.int16(568)),
 (np.int16(568), np.int16(3)),
 (np.int16(3), np.int16(676)),
 (np.int16(676), np.int16(3)),
 (np.int16(3), np.int16(694)),
 (np.int16(694), np.int16(3)),
 (np.int16(3), np.int16(696)),
 (np.int16(696), np.int16(3)),
 (np.int16(3), np.int16(670)),
 (np.int16(670), np.int16(3)),
 (np.int16(3), np.int16(687)),
 (np.int16(687), np.int16(3)),
 (np.int16(3), np.int16(537)),
 (np.int16(537), np.int16(3)),
 (np.int16(3), np.int16(721)),
 (np.int16(721), np.int16(3)),
 (np.int16(3), np.int16(685)),
 (np.int16(685), np.int16(3)),
 (np.int16(3), np.int16(581)),
 (np.int16(581), np.int16(3)),
 (np.int16(4), np.int16(675)),
 (np.int16(675), np.int16(4)),
 (np.int16(4), np.int16(676)),
 (np.int16(676), np.int16(4)),
 (np.int16(4), np.int16(534)),
 (np.int16(534), np.int16(4)),
 (np.int16(4), np.int16(558)),
 (np.int16(558), np.int16(4)),
 (np.int16(4), np.int16(674)),
 (np.int16(674), np.int16(4)),
 (np.int16(4), np.int16(686)),
 (np.int16(686), np.int16(4)),
 (np.int16(4), np.int16(718)),
 (np.int16(718), np.int16(4)),
 (np.int16(4), np.int16(687)),
 (np.int16(687), np.int16(4)),
 (np.int16(4), np.int16(670)),
 (np.int16(670), np.int16(4)),
 (np.int16(4), np.int16(574)),
 (np.int16(574), np.int16(4)),
 (np.int16(4), np.int16(721)),
 (np.int16(721), np.int16(4)),
 (np.int16(4), np.int16(685)),
 (np.int16(685), np.int16(4)),
 (np.int16(4), np.int16(720)),
 (np.int16(720), np.int16(4)),
 (np.int16(4), np.int16(537)),
 (np.int16(537), np.int16(4)),
 (np.int16(4), np.int16(677)),
 (np.int16(677), np.int16(4)),
 (np.int16(4), np.int16(543)),
 (np.int16(543), np.int16(4)),
 (np.int16(4), np.int16(653)),
 (np.int16(653), np.int16(4)),
 (np.int16(5), np.int16(721)),
 (np.int16(721), np.int16(5)),
 (np.int16(5), np.int16(673)),
 (np.int16(673), np.int16(5)),
 (np.int16(5), np.int16(687)),
 (np.int16(687), np.int16(5)),
 (np.int16(5), np.int16(671)),
 (np.int16(671), np.int16(5)),
 (np.int16(5), np.int16(696)),
 (np.int16(696), np.int16(5)),
 (np.int16(5), np.int16(674)),
 (np.int16(674), np.int16(5)),
 (np.int16(5), np.int16(536)),
 (np.int16(536), np.int16(5)),
 (np.int16(5), np.int16(685)),
 (np.int16(685), np.int16(5)),
 (np.int16(5), np.int16(694)),
 (np.int16(694), np.int16(5)),
 (np.int16(5), np.int16(677)),
 (np.int16(677), np.int16(5)),
 (np.int16(5), np.int16(718)),
 (np.int16(718), np.int16(5)),
 (np.int16(5), np.int16(675)),
 (np.int16(675), np.int16(5)),
 (np.int16(5), np.int16(672)),
 (np.int16(672), np.int16(5)),
 (np.int16(5), np.int16(534)),
 (np.int16(534), np.int16(5)),
 (np.int16(5), np.int16(507)),
 (np.int16(507), np.int16(5)),
 (np.int16(6), np.int16(694)),
 (np.int16(694), np.int16(6)),
 (np.int16(6), np.int16(570)),
 (np.int16(570), np.int16(6)),
 (np.int16(6), np.int16(687)),
 (np.int16(687), np.int16(6)),
 (np.int16(6), np.int16(673)),
 (np.int16(673), np.int16(6)),
 (np.int16(6), np.int16(671)),
 (np.int16(671), np.int16(6)),
 (np.int16(6), np.int16(686)),
 (np.int16(686), np.int16(6)),
 (np.int16(6), np.int16(695)),
 (np.int16(695), np.int16(6)),
 (np.int16(6), np.int16(566)),
 (np.int16(566), np.int16(6)),
 (np.int16(6), np.int16(534)),
 (np.int16(534), np.int16(6)),
 (np.int16(6), np.int16(685)),
 (np.int16(685), np.int16(6)),
 (np.int16(6), np.int16(720)),
 (np.int16(720), np.int16(6)),
 (np.int16(6), np.int16(719)),
 (np.int16(719), np.int16(6)),
 (np.int16(6), np.int16(574)),
 (np.int16(574), np.int16(6)),
 (np.int16(6), np.int16(522)),
 (np.int16(522), np.int16(6)),
 (np.int16(6), np.int16(537)),
 (np.int16(537), np.int16(6)),
 (np.int16(6), np.int16(696)),
 (np.int16(696), np.int16(6)),
 (np.int16(7), np.int16(539)),
 (np.int16(539), np.int16(7)),
 (np.int16(7), np.int16(721)),
 (np.int16(721), np.int16(7)),
 (np.int16(7), np.int16(696)),
 (np.int16(696), np.int16(7)),
 (np.int16(7), np.int16(669)),
 (np.int16(669), np.int16(7)),
 (np.int16(7), np.int16(685)),
 (np.int16(685), np.int16(7)),
 (np.int16(7), np.int16(543)),
 (np.int16(543), np.int16(7)),
 (np.int16(7), np.int16(697)),
 (np.int16(697), np.int16(7)),
 (np.int16(7), np.int16(693)),
 (np.int16(693), np.int16(7)),
 (np.int16(7), np.int16(677)),
 (np.int16(677), np.int16(7)),
 (np.int16(7), np.int16(695)),
 (np.int16(695), np.int16(7)),
 (np.int16(7), np.int16(719)),
 (np.int16(719), np.int16(7)),
 (np.int16(7), np.int16(694)),
 (np.int16(694), np.int16(7)),
 (np.int16(7), np.int16(537)),
 (np.int16(537), np.int16(7)),
 (np.int16(7), np.int16(674)),
 (np.int16(674), np.int16(7)),
 (np.int16(7), np.int16(676)),
 (np.int16(676), np.int16(7)),
 (np.int16(7), np.int16(670)),
 (np.int16(670), np.int16(7)),
 (np.int16(8), np.int16(693)),
 (np.int16(693), np.int16(8)),
 (np.int16(8), np.int16(672)),
 (np.int16(672), np.int16(8)),
 (np.int16(8), np.int16(686)),
 (np.int16(686), np.int16(8)),
 (np.int16(8), np.int16(696)),
 (np.int16(696), np.int16(8)),
 (np.int16(8), np.int16(721)),
 (np.int16(721), np.int16(8)),
 (np.int16(8), np.int16(684)),
 (np.int16(684), np.int16(8)),
 (np.int16(8), np.int16(673)),
 (np.int16(673), np.int16(8)),
 (np.int16(8), np.int16(685)),
 (np.int16(685), np.int16(8)),
 (np.int16(8), np.int16(558)),
 (np.int16(558), np.int16(8)),
 (np.int16(8), np.int16(677)),
 (np.int16(677), np.int16(8)),
 (np.int16(8), np.int16(671)),
 (np.int16(671), np.int16(8)),
 (np.int16(8), np.int16(635)),
 (np.int16(635), np.int16(8)),
 (np.int16(8), np.int16(720)),
 (np.int16(720), np.int16(8)),
 (np.int16(8), np.int16(543)),
 (np.int16(543), np.int16(8)),
 (np.int16(8), np.int16(694)),
 (np.int16(694), np.int16(8)),
 (np.int16(8), np.int16(676)),
 (np.int16(676), np.int16(8)),
 (np.int16(8), np.int16(573)),
 (np.int16(573), np.int16(8)),
 (np.int16(9), np.int16(718)),
 (np.int16(718), np.int16(9)),
 (np.int16(9), np.int16(719)),
 (np.int16(719), np.int16(9)),
 (np.int16(9), np.int16(687)),
 (np.int16(687), np.int16(9)),
 (np.int16(9), np.int16(673)),
 (np.int16(673), np.int16(9)),
 (np.int16(9), np.int16(694)),
 (np.int16(694), np.int16(9)),
 (np.int16(9), np.int16(720)),
 (np.int16(720), np.int16(9)),
 (np.int16(9), np.int16(725)),
 (np.int16(725), np.int16(9)),
 (np.int16(9), np.int16(595)),
 (np.int16(595), np.int16(9)),
 (np.int16(9), np.int16(573)),
 (np.int16(573), np.int16(9)),
 (np.int16(9), np.int16(534)),
 (np.int16(534), np.int16(9)),
 (np.int16(9), np.int16(686)),
 (np.int16(686), np.int16(9)),
 (np.int16(9), np.int16(674)),
 (np.int16(674), np.int16(9)),
 (np.int16(9), np.int16(670)),
 (np.int16(670), np.int16(9)),
 (np.int16(9), np.int16(697)),
 (np.int16(697), np.int16(9)),
 (np.int16(9), np.int16(695)),
 (np.int16(695), np.int16(9)),
 (np.int16(9), np.int16(685)),
 (np.int16(685), np.int16(9)),
 (np.int16(9), np.int16(676)),
 (np.int16(676), np.int16(9)),
 (np.int16(9), np.int16(570)),
 (np.int16(570), np.int16(9)),
 (np.int16(10), np.int16(696)),
 (np.int16(696), np.int16(10)),
 (np.int16(10), np.int16(695)),
 (np.int16(695), np.int16(10)),
 (np.int16(10), np.int16(722)),
 (np.int16(722), np.int16(10)),
 (np.int16(10), np.int16(566)),
 (np.int16(566), np.int16(10)),
 (np.int16(10), np.int16(537)),
 (np.int16(537), np.int16(10)),
 (np.int16(10), np.int16(670)),
 (np.int16(670), np.int16(10)),
 (np.int16(10), np.int16(676)),
 (np.int16(676), np.int16(10)),
 (np.int16(10), np.int16(564)),
 (np.int16(564), np.int16(10)),
 (np.int16(10), np.int16(677)),
 (np.int16(677), np.int16(10)),
 (np.int16(10), np.int16(721)),
 (np.int16(721), np.int16(10)),
 (np.int16(10), np.int16(672)),
 (np.int16(672), np.int16(10)),
 (np.int16(10), np.int16(697)),
 (np.int16(697), np.int16(10)),
 (np.int16(10), np.int16(718)),
 (np.int16(718), np.int16(10)),
 (np.int16(10), np.int16(684)),
 (np.int16(684), np.int16(10)),
 (np.int16(10), np.int16(610)),
 (np.int16(610), np.int16(10)),
 (np.int16(10), np.int16(694)),
 (np.int16(694), np.int16(10)),
 (np.int16(10), np.int16(675)),
 (np.int16(675), np.int16(10)),
 (np.int16(10), np.int16(687)),
 (np.int16(687), np.int16(10)),
 (np.int16(11), np.int16(539)),
 (np.int16(539), np.int16(11)),
 (np.int16(11), np.int16(696)),
 (np.int16(696), np.int16(11)),
 (np.int16(11), np.int16(722)),
 (np.int16(722), np.int16(11)),
 (np.int16(11), np.int16(697)),
 (np.int16(697), np.int16(11)),
 (np.int16(11), np.int16(687)),
 (np.int16(687), np.int16(11)),
 (np.int16(11), np.int16(506)),
 (np.int16(506), np.int16(11)),
 (np.int16(11), np.int16(693)),
 (np.int16(693), np.int16(11)),
 (np.int16(11), np.int16(543)),
 (np.int16(543), np.int16(11)),
 (np.int16(11), np.int16(677)),
 (np.int16(677), np.int16(11)),
 (np.int16(11), np.int16(534)),
 (np.int16(534), np.int16(11)),
 (np.int16(11), np.int16(585)),
 (np.int16(585), np.int16(11)),
 (np.int16(11), np.int16(721)),
 (np.int16(721), np.int16(11)),
 (np.int16(11), np.int16(724)),
 (np.int16(724), np.int16(11)),
 (np.int16(11), np.int16(718)),
 (np.int16(718), np.int16(11)),
 (np.int16(11), np.int16(674)),
 (np.int16(674), np.int16(11)),
 (np.int16(11), np.int16(673)),
 (np.int16(673), np.int16(11)),
 (np.int16(12), np.int16(539)),
 (np.int16(539), np.int16(12)),
 (np.int16(12), np.int16(714)),
 (np.int16(714), np.int16(12)),
 (np.int16(12), np.int16(677)),
 (np.int16(677), np.int16(12)),
 (np.int16(12), np.int16(563)),
 (np.int16(563), np.int16(12)),
 (np.int16(12), np.int16(720)),
 (np.int16(720), np.int16(12)),
 (np.int16(12), np.int16(686)),
 (np.int16(686), np.int16(12)),
 (np.int16(12), np.int16(685)),
 (np.int16(685), np.int16(12)),
 (np.int16(12), np.int16(675)),
 (np.int16(675), np.int16(12)),
 (np.int16(12), np.int16(695)),
 (np.int16(695), np.int16(12)),
 (np.int16(12), np.int16(718)),
 (np.int16(718), np.int16(12)),
 (np.int16(12), np.int16(694)),
 (np.int16(694), np.int16(12)),
 (np.int16(12), np.int16(721)),
 (np.int16(721), np.int16(12)),
 (np.int16(12), np.int16(696)),
 (np.int16(696), np.int16(12)),
 (np.int16(12), np.int16(719)),
 (np.int16(719), np.int16(12)),
 (np.int16(12), np.int16(507)),
 (np.int16(507), np.int16(12)),
 (np.int16(12), np.int16(534)),
 (np.int16(534), np.int16(12)),
 (np.int16(12), np.int16(697)),
 (np.int16(697), np.int16(12)),
 (np.int16(12), np.int16(580)),
 (np.int16(580), np.int16(12)),
 (np.int16(13), np.int16(626)),
 (np.int16(626), np.int16(13)),
 (np.int16(13), np.int16(674)),
 (np.int16(674), np.int16(13)),
 (np.int16(13), np.int16(687)),
 (np.int16(687), np.int16(13)),
 (np.int16(13), np.int16(537)),
 (np.int16(537), np.int16(13)),
 (np.int16(13), np.int16(673)),
 (np.int16(673), np.int16(13)),
 (np.int16(13), np.int16(573)),
 (np.int16(573), np.int16(13)),
 (np.int16(13), np.int16(677)),
 (np.int16(677), np.int16(13)),
 (np.int16(13), np.int16(696)),
 (np.int16(696), np.int16(13)),
 (np.int16(13), np.int16(676)),
 (np.int16(676), np.int16(13)),
 (np.int16(13), np.int16(694)),
 (np.int16(694), np.int16(13)),
 (np.int16(13), np.int16(721)),
 (np.int16(721), np.int16(13)),
 (np.int16(13), np.int16(727)),
 (np.int16(727), np.int16(13)),
 (np.int16(13), np.int16(693)),
 (np.int16(693), np.int16(13)),
 (np.int16(13), np.int16(695)),
 (np.int16(695), np.int16(13)),
 (np.int16(13), np.int16(685)),
 (np.int16(685), np.int16(13)),
 (np.int16(13), np.int16(670)),
 (np.int16(670), np.int16(13)),
 (np.int16(14), np.int16(720)),
 (np.int16(720), np.int16(14)),
 (np.int16(14), np.int16(565)),
 (np.int16(565), np.int16(14)),
 (np.int16(14), np.int16(697)),
 (np.int16(697), np.int16(14)),
 (np.int16(14), np.int16(673)),
 (np.int16(673), np.int16(14)),
 (np.int16(14), np.int16(685)),
 (np.int16(685), np.int16(14)),
 (np.int16(14), np.int16(670)),
 (np.int16(670), np.int16(14)),
 (np.int16(14), np.int16(563)),
 (np.int16(563), np.int16(14)),
 (np.int16(14), np.int16(686)),
 (np.int16(686), np.int16(14)),
 (np.int16(14), np.int16(721)),
 (np.int16(721), np.int16(14)),
 (np.int16(14), np.int16(550)),
 (np.int16(550), np.int16(14)),
 (np.int16(14), np.int16(718)),
 (np.int16(718), np.int16(14)),
 (np.int16(14), np.int16(537)),
 (np.int16(537), np.int16(14)),
 (np.int16(14), np.int16(677)),
 (np.int16(677), np.int16(14)),
 (np.int16(14), np.int16(539)),
 (np.int16(539), np.int16(14)),
 (np.int16(14), np.int16(543)),
 (np.int16(543), np.int16(14)),
 (np.int16(14), np.int16(729)),
 (np.int16(729), np.int16(14)),
 (np.int16(14), np.int16(534)),
 (np.int16(534), np.int16(14)),
 (np.int16(15), np.int16(686)),
 (np.int16(686), np.int16(15)),
 (np.int16(15), np.int16(565)),
 (np.int16(565), np.int16(15)),
 (np.int16(15), np.int16(579)),
 (np.int16(579), np.int16(15)),
 (np.int16(15), np.int16(694)),
 (np.int16(694), np.int16(15)),
 (np.int16(15), np.int16(534)),
 (np.int16(534), np.int16(15)),
 (np.int16(15), np.int16(675)),
 (np.int16(675), np.int16(15)),
 (np.int16(15), np.int16(537)),
 (np.int16(537), np.int16(15)),
 (np.int16(15), np.int16(672)),
 (np.int16(672), np.int16(15)),
 (np.int16(15), np.int16(574)),
 (np.int16(574), np.int16(15)),
 (np.int16(15), np.int16(674)),
 (np.int16(674), np.int16(15)),
 (np.int16(15), np.int16(677)),
 (np.int16(677), np.int16(15)),
 (np.int16(15), np.int16(721)),
 (np.int16(721), np.int16(15)),
 (np.int16(15), np.int16(516)),
 (np.int16(516), np.int16(15)),
 (np.int16(15), np.int16(719)),
 (np.int16(719), np.int16(15)),
 (np.int16(15), np.int16(693)),
 (np.int16(693), np.int16(15)),
 (np.int16(15), np.int16(539)),
 (np.int16(539), np.int16(15)),
 (np.int16(15), np.int16(697)),
 (np.int16(697), np.int16(15)),
 (np.int16(16), np.int16(670)),
 (np.int16(670), np.int16(16)),
 (np.int16(16), np.int16(718)),
 (np.int16(718), np.int16(16)),
 (np.int16(16), np.int16(685)),
 (np.int16(685), np.int16(16)),
 (np.int16(16), np.int16(673)),
 (np.int16(673), np.int16(16)),
 (np.int16(16), np.int16(720)),
 (np.int16(720), np.int16(16)),
 (np.int16(16), np.int16(676)),
 (np.int16(676), np.int16(16)),
 (np.int16(16), np.int16(695)),
 (np.int16(695), np.int16(16)),
 (np.int16(16), np.int16(693)),
 (np.int16(693), np.int16(16)),
 (np.int16(16), np.int16(697)),
 (np.int16(697), np.int16(16)),
 (np.int16(16), np.int16(543)),
 (np.int16(543), np.int16(16)),
 (np.int16(16), np.int16(674)),
 (np.int16(674), np.int16(16)),
 (np.int16(16), np.int16(696)),
 (np.int16(696), np.int16(16)),
 (np.int16(16), np.int16(700)),
 (np.int16(700), np.int16(16)),
 (np.int16(16), np.int16(675)),
 (np.int16(675), np.int16(16)),
 (np.int16(16), np.int16(719)),
 (np.int16(719), np.int16(16)),
 (np.int16(16), np.int16(529)),
 (np.int16(529), np.int16(16)),
 (np.int16(16), np.int16(686)),
 (np.int16(686), np.int16(16)),
 (np.int16(16), np.int16(550)),
 (np.int16(550), np.int16(16)),
 (np.int16(17), np.int16(685)),
 (np.int16(685), np.int16(17)),
 (np.int16(17), np.int16(675)),
 (np.int16(675), np.int16(17)),
 (np.int16(17), np.int16(674)),
 (np.int16(674), np.int16(17)),
 (np.int16(17), np.int16(676)),
 (np.int16(676), np.int16(17)),
 (np.int16(17), np.int16(694)),
 (np.int16(694), np.int16(17)),
 (np.int16(17), np.int16(703)),
 (np.int16(703), np.int16(17)),
 (np.int16(17), np.int16(539)),
 (np.int16(539), np.int16(17)),
 (np.int16(17), np.int16(544)),
 (np.int16(544), np.int16(17)),
 (np.int16(17), np.int16(670)),
 (np.int16(670), np.int16(17)),
 (np.int16(17), np.int16(684)),
 (np.int16(684), np.int16(17)),
 (np.int16(17), np.int16(695)),
 (np.int16(695), np.int16(17)),
 (np.int16(17), np.int16(720)),
 (np.int16(720), np.int16(17)),
 (np.int16(17), np.int16(722)),
 (np.int16(722), np.int16(17)),
 (np.int16(17), np.int16(671)),
 (np.int16(671), np.int16(17)),
 (np.int16(17), np.int16(718)),
 (np.int16(718), np.int16(17)),
 (np.int16(17), np.int16(721)),
 (np.int16(721), np.int16(17)),
 (np.int16(17), np.int16(728)),
 (np.int16(728), np.int16(17)),
 (np.int16(18), np.int16(696)),
 (np.int16(696), np.int16(18)),
 (np.int16(18), np.int16(702)),
 (np.int16(702), np.int16(18)),
 (np.int16(18), np.int16(672)),
 (np.int16(672), np.int16(18)),
 (np.int16(18), np.int16(675)),
 (np.int16(675), np.int16(18)),
 (np.int16(18), np.int16(720)),
 (np.int16(720), np.int16(18)),
 (np.int16(18), np.int16(697)),
 (np.int16(697), np.int16(18)),
 (np.int16(18), np.int16(687)),
 (np.int16(687), np.int16(18)),
 (np.int16(18), np.int16(685)),
 (np.int16(685), np.int16(18)),
 (np.int16(18), np.int16(674)),
 (np.int16(674), np.int16(18)),
 (np.int16(18), np.int16(695)),
 (np.int16(695), np.int16(18)),
 (np.int16(18), np.int16(677)),
 (np.int16(677), np.int16(18)),
 (np.int16(18), np.int16(673)),
 (np.int16(673), np.int16(18)),
 (np.int16(18), np.int16(670)),
 (np.int16(670), np.int16(18)),
 (np.int16(18), np.int16(653)),

In [ ]:
edge_index = torch.tensor(edge_list,dtype=torch.long)

In [ ]:
edge_index

tensor([[  0, 720],
        [720,   0],
        [  0, 675],
        ...,
        [652, 499],
        [499, 656],
        [656, 499]])

In [ ]:
edge_index =edge_index.t().contiguous().to(device)

In [ ]:
edge_index

tensor([[  0, 720,   0,  ..., 652, 499, 656],
        [720,   0, 675,  ..., 499, 656, 499]])

In [ ]:
user_pos_items = {user_idx:set() for user_idx in range(num_users)}
for user_idx,item_idx in interactions: 
    user_pos_items[user_idx].add(item_idx)

In [ ]:
user_pos_items

{0: {np.int16(51),
  np.int16(75),
  np.int16(170),
  np.int16(171),
  np.int16(175),
  np.int16(176),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(215),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(221),
  np.int16(225)},
 1: {np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(59),
  np.int16(67),
  np.int16(104),
  np.int16(171),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(219),
  np.int16(221)},
 2: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(171),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(198),
  np.int16(199),
  np.int16(218),
  np.int16(238)},
 3: {np.int16(7),
  np.int16(37),
  np.int16(43),
  np.int16(68),
  np.int16(81),
  np.int16(170),
  np.int16(173),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(187),
  np.int16(194),
  np.int16(196),
  np.int16(219),
  np.int16(221)},
 4: {np.int16(34),
  np.int16(37),
  np.int16(43),
  np.int16(58),
  np.int16(74),
  np.int16(153),
  np.int16(170),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(218),
  np.int16(220),
  np.int16(221)},
 5: {np.int16(7),
  np.int16(34),
  np.int16(36),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(177),
  np.int16(185),
  np.int16(187),
  np.int16(194),
  np.int16(196),
  np.int16(218),
  np.int16(221)},
 6: {np.int16(22),
  np.int16(34),
  np.int16(37),
  np.int16(66),
  np.int16(70),
  np.int16(74),
  np.int16(171),
  np.int16(173),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(219),
  np.int16(220)},
 7: {np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(169),
  np.int16(170),
  np.int16(174),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(219),
  np.int16(221)},
 8: {np.int16(43),
  np.int16(58),
  np.int16(73),
  np.int16(135),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(176),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(196),
  np.int16(220),
  np.int16(221)},
 9: {np.int16(34),
  np.int16(70),
  np.int16(73),
  np.int16(95),
  np.int16(170),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(225)},
 10: {np.int16(37),
  np.int16(64),
  np.int16(66),
  np.int16(110),
  np.int16(170),
  np.int16(172),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(184),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(218),
  np.int16(221),
  np.int16(222)},
 11: {np.int16(6),
  np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(85),
  np.int16(173),
  np.int16(174),
  np.int16(177),
  np.int16(187),
  np.int16(193),
  np.int16(196),
  np.int16(197),
  np.int16(218),
  np.int16(221),
  np.int16(222),
  np.int16(224)},
 12: {np.int16(7),
  np.int16(34),
  np.int16(39),
  np.int16(63),
  np.int16(80),
  np.int16(175),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(214),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(221)},
 13: {np.int16(37),
  np.int16(73),
  np.int16(126),
  np.int16(170),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(221),
  np.int16(227)},
 14: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(50),
  np.int16(63),
  np.int16(65),
  np.int16(170),
  np.int16(173),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(197),
  np.int16(218),
  np.int16(220),
  np.int16(221),
  np.int16(229)},
 15: {np.int16(16),
  np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(65),
  np.int16(74),
  np.int16(79),
  np.int16(172),
  np.int16(174),
  np.int16(175),
  np.int16(177),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(197),
  np.int16(219),
  np.int16(221)},
 16: {np.int16(29),
  np.int16(43),
  np.int16(50),
  np.int16(170),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(200),
  np.int16(218),
  np.int16(219),
  np.int16(220)},
 17: {np.int16(39),
  np.int16(44),
  np.int16(170),
  np.int16(171),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(184),
  np.int16(185),
  np.int16(194),
  np.int16(195),
  np.int16(203),
  np.int16(218),
  np.int16(220),
  np.int16(221),
  np.int16(222),
  np.int16(228)},
 18: {np.int16(153),
  np.int16(170),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(177),
  np.int16(185),
  np.int16(187),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(202),
  np.int16(220)},
 19: {np.int16(37),
  np.int16(39),
  np.int16(50),
  np.int16(69),
  np.int16(114),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(184),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(219),
  np.int16(220),
  np.int16(221)},
 20: {np.int16(43),
  np.int16(70),
  np.int16(71),
  np.int16(91),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(175),
  np.int16(177),
  np.int16(185),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(220),
  np.int16(221),
  np.int16(223)},
 21: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(72),
  np.int16(75),
  np.int16(142),
  np.int16(171),
  np.int16(173),
  np.int16(175),
  np.int16(176),
  np.int16(185),
  np.int16(186),
  np.int16(195),
  np.int16(205),
  np.int16(218),
  np.int16(219),
  np.int16(221)},
 22: {np.int16(7),
  np.int16(37),
  np.int16(43),
  np.int16(118),
  np.int16(171),
  np.int16(172),
  np.int16(174),
  np.int16(175),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(219),
  np.int16(220),
  np.int16(224)},
 23: {np.int16(4),
  np.int16(15),
  np.int16(34),
  np.int16(51),
  np.int16(172),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(225)},
 24: {np.int16(23),
  np.int16(34),
  np.int16(37),
  np.int16(67),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(176),
  np.int16(184),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(219),
  np.int16(221),
  np.int16(224)},
 25: {np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(58),
  np.int16(63),
  np.int16(64),
  np.int16(141),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(195),
  np.int16(197),
  np.int16(218),
  np.int16(220),
  np.int16(221)},
 26: {np.int16(22),
  np.int16(58),
  np.int16(69),
  np.int16(78),
  np.int16(175),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(218),
  np.int16(219),
  np.int16(220)},
 27: {np.int16(39),
  np.int16(67),
  np.int16(80),
  np.int16(158),
  np.int16(170),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(193),
  np.int16(194),
  np.int16(218),
  np.int16(225)},
 28: {np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(67),
  np.int16(71),
  np.int16(99),
  np.int16(170),
  np.int16(172),
  np.int16(173),
  np.int16(175),
  np.int16(185),
  np.int16(186),
  np.int16(196),
  np.int16(219),
  np.int16(221)},
 29: {np.int16(7),
  np.int16(26),
  np.int16(34),
  np.int16(43),
  np.int16(76),
  np.int16(170),
  np.int16(175),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(193),
  np.int16(197),
  np.int16(201),
  np.int16(219),
  np.int16(220),
  np.int16(221)},
 30: {np.int16(34),
  np.int16(43),
  np.int16(87),
  np.int16(171),
  np.int16(175),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(200),
  np.int16(218),
  np.int16(220),
  np.int16(222)},
 31: {np.int16(43),
  np.int16(70),
  np.int16(76),
  np.int16(135),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(175),
  np.int16(184),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(220)},
 32: {np.int16(37),
  np.int16(39),
  np.int16(58),
  np.int16(74),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(197),
  np.int16(218),
  np.int16(221),
  np.int16(228)},
 33: {np.int16(8),
  np.int16(34),
  np.int16(37),
  np.int16(59),
  np.int16(67),
  np.int16(170),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(184),
  np.int16(186),
  np.int16(187),
  np.int16(194),
  np.int16(196),
  np.int16(205),
  np.int16(220)},
 34: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(71),
  np.int16(80),
  np.int16(84),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(174),
  np.int16(176),
  np.int16(195),
  np.int16(196),
  np.int16(201),
  np.int16(221)},
 35: {np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(78),
  np.int16(140),
  np.int16(171),
  np.int16(173),
  np.int16(176),
  np.int16(184),
  np.int16(185),
  np.int16(193),
  np.int16(202),
  np.int16(218),
  np.int16(220),
  np.int16(221)},
 36: {np.int16(34),
  np.int16(37),
  np.int16(65),
  np.int16(79),
  np.int16(173),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(191),
  np.int16(193),
  np.int16(194),
  np.int16(196),
  np.int16(205),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(221)},
 37: {np.int16(7),
  np.int16(11),
  np.int16(34),
  np.int16(39),
  np.int16(78),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(174),
  np.int16(176),
  np.int16(184),
  np.int16(186),
  np.int16(193),
  np.int16(200),
  np.int16(219),
  np.int16(221)},
 38: {np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(69),
  np.int16(158),
  np.int16(170),
  np.int16(173),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(193),
  np.int16(195),
  np.int16(197),
  np.int16(204),
  np.int16(218),
  np.int16(219)},
 39: {np.int16(37),
  np.int16(43),
  np.int16(45),
  np.int16(73),
  np.int16(80),
  np.int16(160),
  np.int16(170),
  np.int16(173),
  np.int16(174),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(218),
  np.int16(219)},
 40: {np.int16(37),
  np.int16(42),
  np.int16(50),
  np.int16(70),
  np.int16(171),
  np.int16(173),
  np.int16(175),
  np.int16(177),
  np.int16(184),
  np.int16(186),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(221)},
 41: {np.int16(4),
  np.int16(33),
  np.int16(43),
  np.int16(76),
  np.int16(170),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(196),
  np.int16(197),
  np.int16(204),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(221)},
 42: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(69),
  np.int16(104),
  np.int16(175),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(221),
  np.int16(224),
  np.int16(226)},
 43: {np.int16(39),
  np.int16(43),
  np.int16(69),
  np.int16(158),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(218)},
 44: {np.int16(37),
  np.int16(39),
  np.int16(45),
  np.int16(59),
  np.int16(67),
  np.int16(110),
  np.int16(171),
  np.int16(175),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(193),
  np.int16(220),
  np.int16(221)},
 45: {np.int16(37),
  np.int16(44),
  np.int16(64),
  np.int16(74),
  np.int16(171),
  np.int16(172),
  np.int16(174),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(219),
  np.int16(241)},
 46: {np.int16(15),
  np.int16(39),
  np.int16(43),
  np.int16(64),
  np.int16(68),
  np.int16(69),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(184),
  np.int16(186),
  np.int16(187),
  np.int16(193),
  np.int16(196),
  np.int16(197),
  np.int16(220)},
 47: {np.int16(34),
  np.int16(37),
  np.int16(43),
  np.int16(59),
  np.int16(80),
  np.int16(94),
  np.int16(170),
  np.int16(171),
  np.int16(173),
  np.int16(174),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(197),
  np.int16(204),
  np.int16(218)},
 48: {np.int16(43),
  np.int16(76),
  np.int16(86),
  np.int16(170),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(219),
  np.int16(220)},
 49: {np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(72),
  np.int16(172),
  np.int16(173),
  np.int16(175),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(197),
  np.int16(204),
  np.int16(215),
  np.int16(218),
  np.int16(219),
  np.int16(221)},
 50: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(45),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(177),
  np.int16(195),
  np.int16(202),
  np.int16(211),
  np.int16(220)},
 51: {np.int16(7),
  np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(44),
  np.int16(45),
  np.int16(130),
  np.int16(176),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(219),
  np.int16(220),
  np.int16(221)},
 52: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(66),
  np.int16(75),
  np.int16(90),
  np.int16(170),
  np.int16(171),
  np.int16(174),
  np.int16(176),
  np.int16(184),
  np.int16(186),
  np.int16(187),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(204),
  np.int16(218),
  np.int16(220)},
 53: {np.int16(37),
  np.int16(39),
  np.int16(50),
  np.int16(65),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(176),
  np.int16(185),
  np.int16(187),
  np.int16(195),
  np.int16(197),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(221),
  np.int16(232)},
 54: {np.int16(4),
  np.int16(7),
  np.int16(12),
  np.int16(34),
  np.int16(39),
  np.int16(50),
  np.int16(170),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(197),
  np.int16(220),
  np.int16(221)},
 55: {np.int16(20),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(50),
  np.int16(171),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(187),
  np.int16(194),
  np.int16(198)},
 56: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(80),
  np.int16(162),
  np.int16(170),
  np.int16(171),
  np.int16(173),
  np.int16(175),
  np.int16(177),
  np.int16(184),
  np.int16(186),
  np.int16(193),
  np.int16(201),
  np.int16(203),
  np.int16(218),
  np.int16(221)},
 57: {np.int16(6),
  np.int16(34),
  np.int16(76),
  np.int16(100),
  np.int16(173),
  np.int16(174),
  np.int16(176),
  np.int16(185),
  np.int16(186),
  np.int16(194),
  np.int16(196),
  np.int16(197),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(222)},
 58: {np.int16(9),
  np.int16(34),
  np.int16(39),
  np.int16(59),
  np.int16(69),
  np.int16(170),
  np.int16(175),
  np.int16(176),
  np.int16(184),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(218),
  np.int16(220)},
 59: {np.int16(34),
  np.int16(37),
  np.int16(73),
  np.int16(75),
  np.int16(131),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(184),
  np.int16(187),
  np.int16(194),
  np.int16(197),
  np.int16(201),
  np.int16(220),
  np.int16(221)},
 60: {np.int16(29),
  np.int16(39),
  np.int16(43),
  np.int16(170),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(197),
  np.int16(200),
  np.int16(206),
  np.int16(218),
  np.int16(219),
  np.int16(220)},
 61: {np.int16(34),
  np.int16(43),
  np.int16(73),
  np.int16(75),
  np.int16(79),
  np.int16(170),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(220),
  np.int16(231)},
 62: {np.int16(1),
  np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(171),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(187),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(219),
  np.int16(220),
  np.int16(221),
  np.int16(225)},
 63: {np.int16(37),
  np.int16(39),
  np.int16(77),
  np.int16(91),
  np.int16(170),
  np.int16(172),
  np.int16(175),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(219),
  np.int16(221)},
 64: {np.int16(4),
  np.int16(39),
  np.int16(59),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(177),
  np.int16(179),
  np.int16(186),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(218),
  np.int16(219),
  np.int16(223)},
 65: {np.int16(10),
  np.int16(34),
  np.int16(43),
  np.int16(72),
  np.int16(79),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(173),
  np.int16(174),
  np.int16(177),
  np.int16(184),
  np.int16(186),
  np.int16(187),
  np.int16(195),
  np.int16(202),
  np.int16(218),
  np.int16(221)},
 66: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(44),
  np.int16(57),
  np.int16(71),
  np.int16(170),
  np.int16(171),
  np.int16(172),
  np.int16(175),
  np.int16(185),
  np.int16(187),
  np.int16(193),
  np.int16(195),
  np.int16(197),
  np.int16(201),
  np.int16(220)},
 67: {np.int16(20),
  np.int16(37),
  np.int16(39),
  np.int16(43),
  np.int16(79),
  np.int16(170),
  np.int16(177),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(219),
  np.int16(220),
  np.int16(221),
  np.int16(225)},
 68: {np.int16(37),
  np.int16(39),
  np.int16(44),
  np.int16(65),
  np.int16(72),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(197),
  np.int16(219),
  np.int16(220),
  np.int16(221),
  np.int16(237)},
 69: {np.int16(0),
  np.int16(37),
  np.int16(39),
  np.int16(44),
  np.int16(69),
  np.int16(171),
  np.int16(172),
  np.int16(174),
  np.int16(184),
  np.int16(185),
  np.int16(187),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(205),
  np.int16(218),
  np.int16(219),
  np.int16(221)},
 70: {np.int16(3),
  np.int16(13),
  np.int16(33),
  np.int16(39),
  np.int16(51),
  np.int16(59),
  np.int16(179),
  np.int16(180),
  np.int16(182),

In [ ]:
def sample_batch(batch_size):
    users =[]
    pos_items = []
    neg_items = []
    for _ in range(batch_size):
        user_idx = random.randint(0,num_users-1)
        pos_item_idx = random.choice(list(user_pos_items[user_idx]))
        while True:
            neg_item_idx = random.randint(0,num_items-1)
            if neg_item_idx not in user_pos_items[user_idx]:
                break
        users.append(user_idx)
        pos_items.append(pos_item_idx)
        neg_items.append(neg_item_idx)
    users = torch.tensor(users,dtype=torch.long).to(device)
    pos_items = torch.tensor(pos_items,dtype=torch.long).to(device)
    neg_items = torch.tensor(neg_items,dtype=torch.long).to(device)
    return users,pos_items,neg_items

In [ ]:
sample_batch(4)

(tensor([302, 455, 382, 377]),
 tensor([ 69, 240,  31, 135]),
 tensor([35, 96, 98, 78]))

In [ ]:
embedding_dim = 64
num_layers = 3
batch_size = 30
epochs = 500
lr = 0.01

In [ ]:
model = LightGCN(num_nodes, embedding_dim, num_layers).to(device)
optimizer = optim.Adam(model.parameters(), lr=lr)

In [ ]:
model.embedding.weight

Parameter containing:
tensor([[-0.0822, -0.0583,  0.0860,  ..., -0.0856,  0.0229,  0.0024],
        [ 0.0113,  0.0681,  0.0630,  ..., -0.0583,  0.0154, -0.0420],
        [-0.0125, -0.0160,  0.0545,  ...,  0.0627,  0.0685,  0.0615],
        ...,
        [ 0.0109, -0.0066,  0.0037,  ...,  0.0569,  0.0153,  0.0321],
        [-0.0012,  0.0698, -0.0161,  ..., -0.0377, -0.0570, -0.0540],
        [ 0.0823, -0.0453, -0.0267,  ...,  0.0242,  0.0767,  0.0478]],
       requires_grad=True)

In [ ]:
model.train()
for epoch in range(epochs):
    users,pos_items,neg_items = sample_batch(batch_size)
    pos_item_nodes = num_users + pos_items
    neg_item_nodes = num_users + neg_items
    #Forward propagation
    final_embeddings = model.get_embedding(edge_index) 

    #BPR loss
    user_emb = final_embeddings[users]
    pos_item_emb = final_embeddings[pos_item_nodes]
    neg_item_emb = final_embeddings[neg_item_nodes]
    pos_scores = torch.sum(user_emb * pos_item_emb, dim=1) # Dot product between user and positive item embeddings
    neg_scores = torch.sum(user_emb * neg_item_emb, dim=1) # Dot product between user and negative item embeddings
    loss = model.recommendation_loss(pos_scores, neg_scores,node_id=users) 

    # Reset gradients
    optimizer.zero_grad()

    # Backpropagation
    loss.backward()
    # Update parameters
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [10/500], Loss: 0.6187
Epoch [20/500], Loss: 0.4308
Epoch [30/500], Loss: 0.3239
Epoch [40/500], Loss: 0.2444
Epoch [50/500], Loss: 0.1805
Epoch [60/500], Loss: 0.0773
Epoch [70/500], Loss: 0.1042
Epoch [80/500], Loss: 0.1439
Epoch [90/500], Loss: 0.1460
Epoch [100/500], Loss: 0.2589
Epoch [110/500], Loss: 0.2955
Epoch [120/500], Loss: 0.1220
Epoch [130/500], Loss: 0.0652
Epoch [140/500], Loss: 0.1366
Epoch [150/500], Loss: 0.1393
Epoch [160/500], Loss: 0.1877
Epoch [170/500], Loss: 0.2209
Epoch [180/500], Loss: 0.1542
Epoch [190/500], Loss: 0.1181
Epoch [200/500], Loss: 0.2332
Epoch [210/500], Loss: 0.1516
Epoch [220/500], Loss: 0.1022
Epoch [230/500], Loss: 0.2272
Epoch [240/500], Loss: 0.0343
Epoch [250/500], Loss: 0.1438
Epoch [260/500], Loss: 0.0983
Epoch [270/500], Loss: 0.1613
Epoch [280/500], Loss: 0.1383
Epoch [290/500], Loss: 0.1054
Epoch [300/500], Loss: 0.0920
Epoch [310/500], Loss: 0.1729
Epoch [320/500], Loss: 0.1734
Epoch [330/500], Loss: 0.0878
Epoch [340/500], Loss: 0.2905
Epoch [350/500], Loss: 0.1761
Epoch [360/500], Loss: 0.0732
Epoch [370/500], Loss: 0.0859
Epoch [380/500], Loss: 0.0727
Epoch [390/500], Loss: 0.1248
Epoch [400/500], Loss: 0.0710
Epoch [410/500], Loss: 0.1397
Epoch [420/500], Loss: 0.1978
Epoch [430/500], Loss: 0.3291
Epoch [440/500], Loss: 0.0485
Epoch [450/500], Loss: 0.2338
Epoch [460/500], Loss: 0.0821
Epoch [470/500], Loss: 0.1073
Epoch [480/500], Loss: 0.2110
Epoch [490/500], Loss: 0.0776
Epoch [500/500], Loss: 0.0784

In [ ]:
@torch.no_grad()
def recommend(user_idx, top_k=10):
    model.eval()
    user_tensor = torch.tensor([user_idx], dtype=torch.long).to(device)
    item_tensor = torch.arange(num_users, num_users + num_items, dtype=torch.long).to(device)
    indices = model.recommend(edge_index=edge_index, src_index=user_tensor, dst_index=item_tensor, k=top_k+100)
    indices = indices[0].tolist()
    recommended_items = [] 
    for idx in indices:
        item_idx = idx-num_users
        if item_idx not in user_pos_items[user_idx]:
            recommended_items.append(item_idx)
        if len(recommended_items) >= top_k:
            break
    return recommended_items

In [ ]:
print("\nRecommend for user 0:")
print(recommend(user_idx=0, top_k=10))

print("\nRecommend for user 1:")
print(recommend(user_idx=1, top_k=10))

Recommend for user 0:
[173, 196, 174, 195, 172, 187, 37, 194, 34, 43]

Recommend for user 1:
[185, 186, 187, 220, 172, 37, 184, 218, 170, 177]

In [ ]:
model.get_embedding(edge_index)

tensor([[ 0.2573,  0.1684, -0.2663,  ...,  0.0727, -0.1280, -0.2208],
        [ 0.4850,  0.2719, -0.4013,  ...,  0.2497, -0.1143, -0.2683],
        [ 0.2982,  0.0973, -0.2435,  ...,  0.2776,  0.0104, -0.1820],
        ...,
        [-0.6200, -0.6516,  0.7377,  ...,  0.5721,  0.4470,  0.4743],
        [-0.4566, -0.5406,  0.5584,  ...,  0.3608,  0.0966,  0.2397],
        [-0.4695, -0.4301,  0.5475,  ...,  0.3971,  0.3722,  0.4276]],
       grad_fn=<AddBackward0>)

In [ ]:
def get_mapping(df): 
    product_idx_to_id = dict(zip(df["product_idx"], df["product_id"]))
    product_id_to_idx = dict(zip(df["product_id"], df["product_idx"]))
    user_id_to_idx = dict(zip(df["user_id"], df["user_idx"]))
    user_idx_to_id = dict(zip(df["user_idx"], df["user_id"]))
    return product_idx_to_id, product_id_to_idx, user_id_to_idx, user_idx_to_id

In [ ]:
product_idx_to_id_mapping, product_id_to_idx_mapping, user_id_to_idx_mapping, user_idx_to_id_mapping = get_mapping(user_product_interactions)

In [ ]:
item_embeddings = model.get_embedding(edge_index)[num_users:].detach().numpy()
user_embeddings = model.get_embedding(edge_index)[:num_users].detach().numpy()

In [ ]:

joblib.dump(user_id_to_idx_mapping, "../models/lightgcn/user_id_to_idx_mapping.joblib")
joblib.dump(user_idx_to_id_mapping, "../models/lightgcn/user_idx_to_id_mapping.joblib")
joblib.dump(product_id_to_idx_mapping, "../models/lightgcn/product_id_to_idx_mapping.joblib")
joblib.dump(product_idx_to_id_mapping, "../models/lightgcn/product_idx_to_id_mapping.joblib")
joblib.dump(item_embeddings, "../models/lightgcn/item_embeddings.joblib")
joblib.dump(user_embeddings, "../models/lightgcn/user_embeddings.joblib")

['../models/lightgcn/user_embeddings.joblib']